### ISSUE TITLE
Use aws-sdk

### ISSUE THREAD

**Issue by dtan4** [dtan4/terraforming#2]
## WHAT

Use [aws-sdk](https://github.com/aws/aws-sdk-ruby) gem to fetch resource information instead of awscli output

## TODO

- [x] Database Parameter Group #9 
- [x] Database Security Group #7
- [x] Database Parameter Group #8 
- [x] EC2 #19 
- [x] ELB #5 
- [x] RDS #3 
- [x] S3 #4 
- [x] Security Group #11
- [x] VPC #18

**Comment by dtan4** [comment]
Close!
