### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by dtan4** [dtan4/terraforming#208]
## WHY

Thankfully, Terraforming is now used by many people. Some companies (incl. my belonging) are using in Production.

[Semantic Versioning 2.0.0](http://semver.org/) defines that: 

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

According to these definitions, current version v0.7.0 seems to be unstable and not yet GA. Over a year has passed since I started developing Terraforming, so it's time to release GA.
## WHAT

Release v1.0.0.
## TODO
- [x] Drop Ruby 2.0 support #206 
- Update dependencies
  - [x] aws-sdk #209 
  - [x] Ox #210 
- [ ] Modify application description
- [x] CONTRIBUTING.md
- [ ] Plugin-based architecture (https://github.com/dtan4/terraforming/issues/152)

**Comment by sasukeh** [comment]
Tew yeas past. Is there any update?

**Comment by dtan4** [comment]
This issue is very stale... I'll reopen this once I come up with an new idea...
